include:
  # One Up Chuck Dongle (optional)
  - board: seeeduino_xiao_ble
    shield: one_up_chuck_dongle dongle_adapter
    snippet: studio-rpc-usb-uart
    artifact-name: chuck-dongle

  # One Up Chuck can either be a unibody (no dongle) or peripheral (with dongle)
  - board: seeeduino_xiao_ble
    shield: one_up_chuck_unibody rgbled_adapter
    snippet: studio-rpc-usb-uart
    artifact-name: chuck-unibody
  - board: seeeduino_xiao_ble
    shield: one_up_chuck_peripheral rgbled_adapter
    artifact-name: chuck-peripheral
