parse_config:
  modifier_fn_map:
    left_shift: ⇧
    left_alt: ⌥
    right_alt: Alt
    left_ctrl: ^
    left_gui: ⌘
    keycode_combiner: "{mods}{key}"
    mod_combiner: "{mod_1}{mod_2}"

  raw_binding_map:
    "&bt_sel 0": BT 1
    "&bt_sel 1": BT 2
    "&bt_sel 2": BT 3
    "&bt_sel 3": BT 4
    "&bt_sel 4": BT 5
    "&bt_clr 0": clear 1
    "&bt_clr 1": clear 2
    "&bt_clr 2": clear 3
    "&bt_clr 3": clear 4
    "&bt_clr 4": clear 5
    "&caps_word": caps word
    "&flash 4": flash
    "&ind_bat": battery status
    "&ind_con": connection status
    "&sk LSHIFT": sticky ⇧
    "&studio_unlock": ZMK Studio
    "&usb_sel": USB
    GS(N4): screen shot
    GCS(N4): screen copy
    GC(Q): lock screen

  zmk_keycode_map:
    AMPS: "&"
    AT: "@"
    BACKSLASH: \
    BSPC: ⌫
    CAPS: Caps 🔒
    CARET: ^
    COLON: ":"
    COMMA: ","
    C_NEXT: ⏭
    C_PP: ⏯
    C_PREV: ⏮
    DEL: ⌦
    DLLR: $
    DOT: .
    DOWN: ↓
    END: End
    EQUAL: "="
    ESC: Esc
    EXCL: "!"
    GLOBE: 🌐
    GRAVE: "`"
    GT: ">"
    HASH: "#"
    HOME: Home
    KP_NUM: Num 🔒
    LALT: ⌥
    LBKT: "["
    LBRC: "{"
    LCTL: ^
    LCTRL: ^
    LEFT: ←
    LGUI: ⌘
    LPAR: (
    LSHFT: ⇧
    LT: <
    MINUS: "-"
    PG_DN: PgDn
    PG_UP: PgUp
    PIPE: "|"
    PLUS: +
    PRCNT: "%"
    QMARK: "?"
    RALT: Alt
    RBKT: "]"
    RBRC: "}"
    RET: ↵
    RIGHT: →
    RPAR: )
    SEMI: ;
    SLASH: /
    SPC: ␣
    SQT: "'"
    STAR: "*"
    TAB: ⇥
    TILDE: "~"
    UNDER: _
    UP: ↑

  zmk_combos:
    combo_esc:
      draw_separate: true
    combo_tab:
      draw_separate: true
    combo_backspace:
      draw_separate: true
    combo_return:
      draw_separate: true
    combo_up:
      layers: [flash mode]
    combo_down:
      layers: [flash mode]
    combo_left:
      layers: [flash mode]
    combo_right:
      layers: [flash mode]
    combo_scroll_up:
      layers: [flash mode]
    combo_scroll_down:
      layers: [flash mode]
    combo_scroll_left:
      layers: [flash mode]
    combo_scroll_right:
      layers: [flash mode]
