parse_config:
  modifier_fn_map:
    left_shift: ⇧
    left_alt: ⌥
    right_alt: Alt
    left_ctrl: ^
    left_gui: ⌘
    keycode_combiner: "{mods}{key}"
    mod_combiner: "{mod_1}{mod_2}"

  raw_binding_map:
    "&bt_sel 0": BT 1
    "&bt_sel 1": BT 2
    "&bt_sel 2": BT 3
    "&bt_sel 3": BT 4
    "&bt_sel 4": BT 5
    "&bt_clr 0": clear 1
    "&bt_clr 1": clear 2
    "&bt_clr 2": clear 3
    "&bt_clr 3": clear 4
    "&bt_clr 4": clear 5
    "&caps_word": caps word
    "&flash 4": flash
    "&ind_bat": battery status
    "&ind_con": connection status
    "&sk LSHIFT": sticky ⇧
    "&studio_unlock": ZMK Studio
    "&usb_sel": USB
    GS(N4): screen shot
    GCS(N4): screen copy
    GC(Q): lock screen

  zmk_keycode_map:
    BSPC: ⌫
    DEL: ⌦
    ESC: Esc
    RET: ↵
    TAB: ⇥
    UP: ↑
    DOWN: ↓
    LEFT: ←
    RIGHT: →
    HOME: Home
    END: End
    PG_UP: PgUp
    PG_DN: PgDn
    LALT: ⌥
    RALT: Alt
    LCTL: ^
    LCTRL: ^
    LGUI: ⌘
    LSHFT: ⇧
    C_PP: ⏯
    C_PREV: ⏮
    C_NEXT: ⏭
    SPC: ␣
    CAPS: Caps 🔒
    KP_NUM: Num 🔒

  zmk_combos:
    combo_esc:
      align: top
      offset: 0.25
    combo_tab:
      align: top
      offset: 0.25
    combo_backspace:
      align: top
      offset: 0.25
    combo_return:
      align: top
      offset: 0.25
    combo_up:
      layers: sym / nav
    combo_down:
      layers: sym / nav
    combo_left:
      layers: sym / nav
    combo_right:
      layers: sym / nav
