M48
; DRILL file {KiCad 8.0.7} date 2024-12-24T09:40:12-0700
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-12-24T09:40:12-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0295
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0354
%
G90
G05
T1
X9.3029Y-1.7664
X9.3309Y-1.871
T2
X7.1055Y-1.3141
X7.2236Y-1.3141
M30
